name: Bug Report
description: The software does something unwanted or unusual
title: "[BUG]: "
labels: ["bug"]

body:
  - type: markdown
    attributes: 
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: new-bug
    attributes:
      label: Did you search for similar bugs?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: false
  - type: textarea
    id: bug-description
    attributes:
      label: What happened?
      description: Tell us what bug you encountered
    validations:
      required: true
  - type: textarea
    id: bug-behaviour
    attributes:
      label: Expectations?
      description: Tell us what should have happened
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: Can you describe your steps, when you encountered the bug?
      placeholder: Please write the steps in a list form
    validations:
      required: false